"""FastAPI application — AI Proposal Generator v2."""

import os
import time
import glob
import asyncio
from datetime import datetime, timezone
from urllib.parse import urlparse
import ipaddress

import requests as http_requests
from fastapi import FastAPI, BackgroundTasks, HTTPException, Query, Request
from fastapi.responses import FileResponse, JSONResponse, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.config import settings
from app.logger import get_logger
from app.schemas import ProposalRequest, ProposalResponse, HealthResponse, EditProposalRequest
from app.prompt_builder import build_prompt, build_edit_prompt
from app.generator import generate_proposal
from app.cost_logic import calculate_cost, save_cost_report, estimate_team_composition
from app.pdf_builder import build_proposal_pdf
from app.db import init_db, register_device, get_device_info, record_proposal, get_device_proposals, get_proposal_sections

log = get_logger(__name__)

_start_time = time.time()

# ── Initialise SQLite DB on startup ──────────────────────────────────────────
try:
    init_db()
    log.info("SQLite session DB initialised.")
except Exception as _db_err:
    log.warning("DB init failed (non-fatal): %s", _db_err)

app = FastAPI(
    title=settings.app_title,
    version=settings.app_version,
    description="AI-powered consulting proposal automation — generate professional proposals with deterministic cost logic.",
)

# ---- CORS ----
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---- Serve frontend static files ----
_frontend_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend")
if os.path.isdir(_frontend_dir):
    app.mount("/static", StaticFiles(directory=_frontend_dir), name="frontend")

@app.get("/")
def read_root():
    """Serve the main index.html."""
    index_path = os.path.join(_frontend_dir, "index.html")
    if os.path.isfile(index_path):
        return FileResponse(index_path)
    return {
        "message": f"{settings.app_title} API v{settings.app_version} is running!",
        "docs": "/docs",
        "health": "/health",
    }


@app.get("/health", response_model=HealthResponse)
def health_check():
    """Health / readiness probe."""
    return HealthResponse(
        status="healthy",
        version=settings.app_version,
        uptime_seconds=round(time.time() - _start_time, 2),
    )


# ──────────────────────────────────────────────────────────────────────────── #
#  SESSION / DEVICE ENDPOINTS                                                    #
# ──────────────────────────────────────────────────────────────────────────── #

@app.post("/session/register")
def session_register(
    device_id: str = Query(..., min_length=10, max_length=128),
    user_name: str = Query(default="", max_length=80),
):
    """Register or refresh a device session. Accepts optional user_name."""
    try:
        info = register_device(device_id, user_name=user_name)
        return info
    except Exception as e:
        log.error("session_register error: %s", e)
        return JSONResponse(status_code=500, content={"error": str(e)})


@app.get("/session/{device_id}")
def session_info(device_id: str):
    """Return device info and proposal history for persistence across sessions."""
    info = get_device_info(device_id)
    if not info:
        raise HTTPException(status_code=404, detail="Device not registered")
    history = get_device_proposals(device_id)
    return {"device": info, "history": history}


@app.get("/session/{device_id}/proposals")
def session_proposals(device_id: str):
    """List proposals generated by this device with file size info."""
    rows = get_device_proposals(device_id)
    output_dir = settings.output_dir
    result = []
    for r in rows:
        fp = os.path.join(output_dir, r["filename"])
        size_kb = round(os.path.getsize(fp) / 1024, 1) if os.path.isfile(fp) else 0
        result.append({
            **r,
            "size_kb": size_kb,
            "exists": os.path.isfile(fp),
            "download_url": f"/proposals/{r['filename']}",
            "view_url": f"/proposals/{r['filename']}?inline=true",
        })
    return {"proposals": result}


# ──────────────────────────────────────────────────────────────────────────── #
# Shared SSRF protection helper for Ollama-facing endpoints                     #
# ──────────────────────────────────────────────────────────────────────────── #
def _validate_ollama_url(url: str):
    """Return (base_url, None) if valid loopback URL, or (None, error_response)."""
    parsed = urlparse(url)
    hostname = parsed.hostname or ""
    allowed_hosts = {"localhost", "127.0.0.1", "::1"}
    try:
        ip = ipaddress.ip_address(hostname)
        if not ip.is_loopback:
            return None, JSONResponse(status_code=400, content={"connected": False, "error": "Only loopback/localhost URLs are allowed for security."})
    except ValueError:
        if hostname not in allowed_hosts:
            return None, JSONResponse(status_code=400, content={"connected": False, "error": "Only loopback/localhost URLs are allowed for security."})
    return url.rstrip("/"), None


# ──────────────────────────────────────────────────────────────────────────── #
@app.get("/ollama-status")
def ollama_status(url: str = Query(default="http://localhost:11434")):
    """Check if Ollama is reachable and return all installed models with cloud/local tag."""
    base, err = _validate_ollama_url(url)
    if err:
        return err

    try:
        resp = http_requests.get(f"{base}/api/tags", timeout=5)
        resp.raise_for_status()
        data = resp.json()
        all_models = data.get("models", [])
        models = [
            {
                "name": m["name"],
                "is_cloud": ":cloud" in m.get("name", ""),
                "size": m.get("size", 0),
                "size_gb": round(m.get("size", 0) / (1024**3), 2) if m.get("size", 0) > 1000 else 0,
                "modified_at": m.get("modified_at", ""),
                "family": m.get("details", {}).get("family", ""),
                "parameter_size": m.get("details", {}).get("parameter_size", ""),
                "quantization": m.get("details", {}).get("quantization_level", ""),
            }
            for m in all_models
        ]
        local_count = sum(1 for m in models if not m["is_cloud"])
        return {
            "connected": True,
            "url": base,
            "models": models,
            "model_count": local_count,
            "total_models_including_cloud": len(all_models),
        }
    except http_requests.exceptions.ConnectionError:
        return JSONResponse(status_code=503, content={"connected": False, "url": base, "models": [], "model_count": 0, "error": "Cannot connect to Ollama. Make sure it is running."})
    except Exception as e:
        return JSONResponse(status_code=503, content={"connected": False, "url": base, "models": [], "model_count": 0, "error": str(e)})


@app.post("/ollama-pull")
async def ollama_pull_model(model_name: str = Query(..., min_length=1), url: str = Query(default="http://localhost:11434")):
    """Trigger a model pull on Ollama (non-streaming, async). Returns success/failure."""
    base, err = _validate_ollama_url(url)
    if err:
        return err

    def _do_pull():
        resp = http_requests.post(
            f"{base}/api/pull",
            json={"name": model_name, "stream": False},
            timeout=600,
        )
        resp.raise_for_status()
        return resp

    log.info("Pulling Ollama model: %s", model_name)
    try:
        await asyncio.to_thread(_do_pull)
        return {"success": True, "model": model_name, "message": f"Model '{model_name}' pulled successfully."}
    except http_requests.exceptions.ConnectionError:
        return JSONResponse(status_code=503, content={"success": False, "error": "Cannot connect to Ollama."})
    except http_requests.exceptions.Timeout:
        return JSONResponse(status_code=504, content={"success": False, "error": "Model pull timed out. Try manually: ollama pull " + model_name})
    except Exception as e:
        return JSONResponse(status_code=500, content={"success": False, "error": str(e)})


@app.post("/generate-proposal", response_model=ProposalResponse)
def generate(data: ProposalRequest, background_tasks: BackgroundTasks):
    """Generate a structured consulting proposal (JSON response)."""
    log.info("Generating proposal: %s (%s, %d months)", data.project_title, data.industry, data.duration_months)

    provider_opts = {
        "provider": data.provider,
        "model": data.model,
        "api_key": data.api_key,
        "api_url": data.api_url,
    }
    
    prompt = build_prompt(data)
    expected_weeks = data.duration_months * 4
    sections = generate_proposal(prompt, expected_weeks=expected_weeks, provider_opts=provider_opts)

    cost_data = calculate_cost(data.duration_months, data.expected_users)
    team = estimate_team_composition(data.duration_months, data.expected_users, data.tech_stack)

    # Persist cost report files in background
    try:
        background_tasks.add_task(save_cost_report, cost_data)
    except Exception as e:
        log.warning("Failed to schedule cost report save: %s", e)

    return {
        "executive_summary": sections["executive_summary"],
        "technical_approach": sections["technical_approach"],
        "timeline": sections["timeline"],
        "estimated_cost": cost_data,
        "risk_assessment": sections["risk_assessment"],
        "deliverables": sections["deliverables"],
        "team_composition": team,
    }


@app.post("/download-proposal-pdf")
def download_pdf(data: ProposalRequest):
    """Generate and return the proposal as a downloadable PDF."""
    log.info("Generating PDF for: %s", data.project_title)

    provider_opts = {
        "provider": data.provider,
        "model": data.model,
        "api_key": data.api_key,
        "api_url": data.api_url,
    }

    prompt = build_prompt(data)
    expected_weeks = data.duration_months * 4
    sections = generate_proposal(prompt, expected_weeks=expected_weeks, provider_opts=provider_opts)
    cost_data = calculate_cost(data.duration_months, data.expected_users)
    team = estimate_team_composition(data.duration_months, data.expected_users, data.tech_stack)

    proposal_for_pdf = {
        "project_title": data.project_title,
        "client_name": data.client_name or "",
        "industry": data.industry,
        "duration_months": data.duration_months,
        "expected_users": data.expected_users,
        "tech_stack": data.tech_stack,
        "executive_summary": sections["executive_summary"],
        "technical_approach": sections["technical_approach"],
        "timeline": sections["timeline"],
        "estimated_cost": cost_data,
        "risk_assessment": sections["risk_assessment"],
        "deliverables": sections["deliverables"],
        "team_composition": team,
    }

    pdf_path = build_proposal_pdf(proposal_for_pdf)
    safe_title = data.project_title.replace(" ", "_").replace("/", "_")
    pdf_filename = os.path.basename(pdf_path)

    # Record in device session DB if device_id provided
    proposal_id = None
    if data.device_id:
        try:
            proposal_id = record_proposal(
                device_id=data.device_id,
                filename=pdf_filename,
                title=data.project_title,
                client=data.client_name or "",
                industry=data.industry,
                months=data.duration_months,
                users=data.expected_users,
                provider=data.provider or "ollama",
                model=data.model or "auto",
                sections=sections,
            )
        except Exception as e:
            log.warning("record_proposal failed: %s", e)

    extra_headers = {"Content-Disposition": f'attachment; filename="{safe_title}_Proposal.pdf"'}
    if proposal_id:
        extra_headers["X-Proposal-Id"] = str(proposal_id)
        extra_headers["Access-Control-Expose-Headers"] = "X-Proposal-Id"

    return FileResponse(
        path=pdf_path,
        media_type="application/pdf",
        filename=f"{safe_title}_Proposal.pdf",
        headers=extra_headers,
    )


@app.post("/edit-proposal", response_model=ProposalResponse)
def edit_proposal(data: EditProposalRequest):
    """Edit an existing proposal using AI with full context awareness."""
    log.info("Editing proposal: %s — instruction: %.80s", data.project_title, data.edit_instruction)

    provider_opts = {
        "provider": data.provider,
        "model": data.model,
        "api_key": data.api_key,
        "api_url": data.api_url,
    }

    original_data = {
        "project_title": data.project_title,
        "industry": data.industry,
        "duration_months": data.duration_months,
        "expected_users": data.expected_users,
        "tech_stack": data.tech_stack,
        "client_name": data.client_name,
    }

    prompt = build_edit_prompt(original_data, data.current_sections, data.edit_instruction)
    expected_weeks = data.duration_months * 4
    sections = generate_proposal(prompt, expected_weeks=expected_weeks, provider_opts=provider_opts)

    cost_data = calculate_cost(data.duration_months, data.expected_users)
    team = estimate_team_composition(data.duration_months, data.expected_users, data.tech_stack)

    return {
        "executive_summary": sections["executive_summary"],
        "technical_approach": sections["technical_approach"],
        "timeline": sections["timeline"],
        "estimated_cost": cost_data,
        "risk_assessment": sections["risk_assessment"],
        "deliverables": sections["deliverables"],
        "team_composition": team,
    }


@app.get("/proposals")
def list_proposals():
    """List previously generated proposal PDFs and cost reports."""
    output_dir = settings.output_dir
    if not os.path.isdir(output_dir):
        return {"proposals": [], "cost_reports": []}

    pdfs = []
    for fp in sorted(glob.glob(os.path.join(output_dir, "proposal_*.pdf")), reverse=True):
        stat = os.stat(fp)
        pdfs.append({
            "filename": os.path.basename(fp),
            "created_at": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
            "size_kb": round(stat.st_size / 1024, 1),
            "download_url": f"/proposals/{os.path.basename(fp)}",
        })

    cost_files = []
    for fp in sorted(glob.glob(os.path.join(output_dir, "cost_report_*.json")), reverse=True):
        stat = os.stat(fp)
        cost_files.append({
            "filename": os.path.basename(fp),
            "created_at": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
            "size_kb": round(stat.st_size / 1024, 1),
        })

    return {"proposals": pdfs, "cost_reports": cost_files}


@app.get("/proposals/{filename}")
def serve_proposal(filename: str, inline: bool = Query(default=False)):
    """Serve an existing proposal PDF. Use ?inline=true for browser inline viewing."""
    safe_name = os.path.basename(filename)  # prevent path traversal
    filepath = os.path.join(settings.output_dir, safe_name)

    if not os.path.isfile(filepath):
        raise HTTPException(status_code=404, detail="Proposal not found")

    disposition = "inline" if inline else "attachment"
    return FileResponse(
        path=filepath,
        media_type="application/pdf",
        filename=safe_name,
        headers={"Content-Disposition": f'{disposition}; filename="{safe_name}"'},
    )
